/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn zbesh_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        m: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zbesi_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zbesj_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zbesk_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zbesy_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        cwrkr: *mut f64,
        cwrki: *mut f64,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zairy_(
        zr: *const f64,
        zi: *const f64,
        id: *const ::std::os::raw::c_int,
        kode: *const ::std::os::raw::c_int,
        air: *mut f64,
        aii: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn zbiry_(
        zr: *const f64,
        zi: *const f64,
        id: *const ::std::os::raw::c_int,
        kode: *const ::std::os::raw::c_int,
        bir: *mut f64,
        bii: *mut f64,
        ierr: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn dgamln_(z: *const f64, ierr: *mut ::std::os::raw::c_int) -> f64;
}
