/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn zbesi_(
        zr: *const f64,
        zi: *const f64,
        fnu: *const f64,
        kode: *const ::std::os::raw::c_int,
        n: *const ::std::os::raw::c_int,
        cyr: *mut f64,
        cyi: *mut f64,
        nz: *mut ::std::os::raw::c_int,
        ierr: *mut ::std::os::raw::c_int,
    );
}
